\documentclass{article}
\usepackage{tabularx}

\begin{document}
\SweaveOpts{concordance=TRUE}
\renewcommand{\arraystretch}{1.5}


\begin{table}
\caption{Simplified Time Value of Money Equations}
\centering
\begin{tabular}[htb]{l|l}
Factor Notation & Equation\\
\hline
(F|P,i,N) & $F=P(1+i)^N$\\
(P|F,i,N) & $P=\frac{F}{(1+i)^N}$\\
(F|A,i,N) & $F=A\left(\frac{(1+i)^{N}-1}{i}\right)$\\
\hline
(A|F,i,N) & $A=F\left(\frac{i}{(1+i)^{N}-1}\right)$\\
(P|A,i,N) & $P=A\left(\frac{(1+i)^{N}-1}{i(1+i)^{N}}\right)$\\
(A|P,i,N) & $A=P\left(\frac{i(1+i)^{N}}{(1+i)^{N}-1}\right)$\\
\hline
(P|G,i,N) &$P=G\left(\frac{(1+i)^{N}-iN-1}{i^{2}(1+i)^{N}}\right)$\\
\hline
(P|$A_1$,i,g,N) & $P=A_{1}\left(\frac{1-(1+g)^{N}(1+i)^{-N}}{i-g}\right)$ \\
 ~&  or $P=A_{1}\left(\frac{N}{1+i}\right)\,(if : i = g)$ \\


\end{tabular}
\end{table}


\begin{table}
\caption{Accounting Ratios}
\centering
\begin{tabular}[htb]{l|c}
Ratio & Definition\\
\hline
Debt Ratio & $\frac{\mathrm{Total ~ Liabilities}}{\mathrm{Total ~ Assets}}$ \\

Times Interest Earned Ratio & $ \frac{\mathrm{Earnings~before~ Interest ~and ~Taxes}}{\mathrm{Interest ~Expense}} $\\

Current Ratio  & $ \frac{\mathrm{Current ~Assets}}{\mathrm{Current~Liabilities}}$\\

Quick Ratio & $ \frac{\mathrm{Current ~Assets}- \mathrm{Inventory}}{\mathrm{Current~Liabilities}}$\\

Inventory Turnover &  $\frac{\mathrm{Total~ Revenue}}{\mathrm{Average ~inventory ~balance}}$\\
Total Asset Turnover &  $\frac{\mathrm{Total~Revenue}}{\mathrm{Total~assets}}$\\

Accounts Receivable Turnover&  $\frac{\mathrm{Accounts ~Receivable}}{\mathrm{Average~daily~sales}}$\\

Profit Margin on Sales&  $\frac{\mathrm{Net~Income}- \mathrm{Preferred~dividends}}{\mathrm{Total Revenue}}$\\

Return on Total Assets&  $\frac{\mathrm{Earnings~before~interest~and ~taxes}}{\mathrm{Total~Assets}}$\\

Return on Common Equity&  $\frac{\mathrm{Net ~Income}-\mathrm{Preferred~Dividends}}{\mathrm{Common~Stock}+\mathrm{Retained~Earnings}+\mathrm{Capital~Surplus}}$\\

Price/Earnings Ratio&  $\frac{\mathrm{Price~per~share}}{\mathrm{Earnings per share}}$\\
\end{tabular}
\end{table}

\end{document}